---
title: "Assignment-2"
author: "Manasa Chelukala"
date: '2022-09-22'
output:
  pdf_document: default
  html_document: default
---
LP Model using R
```{r}
#Installing the lpSolve library
library(lpSolve)

```

```{r}
# Set Objective function
f.obj <- c(420,360,300,
           420,360,300,
           420,360,300)
```

```{r}
#Set the Constraints
f.con <-matrix(c(1,1,1,0,0,0,0,0,0,
                 0,0,0,1,1,1,0,0,0,
                 0,0,0,0,0,0,1,1,1,
                 20,15,12,0,0,0,0,0,0,
                 0,0,0,20,15,12,0,0,0,
                 0,0,0,0,0,0,20,15,12,
                 1,0,0,1,0,0,1,0,0,
                 0,1,0,0,1,0,0,1,0,
                 0,0,1,0,0,1,0,0,1) , nrow = 9,byrow = TRUE)
```


```{r}
#Set the direction of the inequalities
f.dir<-c("<=",
         "<=",
         "<=",
         "<=",
         "<=",
         "<=",
         "<=",
         "<=",
         "<=")
```

```{r}
#Set the right hand side coefficients
f.rhs<-c(750,
        900,
        450,
        13000,
        12000,
        5000,
        900,
        1200,
        750)
```

```{r}
#Find the value of the objective function(Z)
lp("max",f.obj,f.con,f.dir,f.rhs)
```
```{r}
#Values of the variables
lp("max", f.obj, f.con, f.dir, f.rhs)$solution
```

